name: veno
description: Flutter plugin.
homepage: https://github.com/qq15725/flutter-veno/tree/master/packages/veno
version: 0.0.2

dependencies:
  flutter:
    sdk: flutter
  veno_router: ^0.0.2
  veno_model: ^0.0.2
  veno_container: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"