name: veno
description: Flutter plugin.
version: 0.0.1
dependencies:
  flutter:
    sdk: flutter
  veno_router: ^0.0.1
  veno_model: ^0.0.1
  veno_container: ^0.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"