name: veno_model
description: Flutter plugin.
homepage: https://github.com/qq15725/flutter-veno/tree/master/packages/veno_model
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"